# Generated by Django 3.1.5 on 2021-01-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Portfolio_model',
        ),
    ]
