# Generated by Django 3.2 on 2021-04-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20210105_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='portfolio/image/')),
                ('marital_status', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio_model',
        ),
    ]
