# Generated by Django 3.2 on 2021-04-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_auto_20210422_0537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal_details',
            new_name='Personal_detail',
        ),
    ]
