# Generated by Django 3.2 on 2021-04-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_rename_personal_details_personal_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoCurricular_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('position', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('expert_level', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='personal_detail',
            name='hobby',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
